version: '3'

services:
  database:
    image: mysql:8.0.26
    container_name: codeflix_video_catalog_database
    ports: 
      - 3307:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./tables.sql:/docker-entrypoint-initdb.d/1.sql
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - MYSQL_DATABASE=video_catalog
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - app-network

  app:
    build: .
    container_name: codeflix_video_catalog
    entrypoint: dockerize -wait tcp://database:3306 -timeout 50s ./start.sh
    ports: 
      - 9000:8080
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
      - DATABASE_DBNAME=video_catalog
    networks: 
      - app-network
    depends_on: 
      - database
  
networks: 
  app-network:
    driver: bridge