spring:
    jpa:
        hibernate:
            ddl-auto: none
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
    datasource:
        url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_DBNAME:video_catalog}?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
        username: ${DATABASE_USER:root}
        password: ${DATABASE_PASSWORD:123456}
        driver-class-name: com.mysql.cj.jdbc.Driver
